name: "Build Job"
on:
  push: 
    branches: [ main ]
  workflow_dispatch:  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Setup NodeJs"
        uses: actions/setup-node@v4
        with:
         node-version: '18'
      - name: "Install Dependencies"
        run: npm install
      - name: "Run liniting"
        run: npm run lint
        continue-on-error: true
      - name: "Build the application"
        run: npm run build
        continue-on-error: true
      - name: "Final Step"
        run: echo "All steps are passed"

